name: glowshoess.id
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: 1.2.2
  webview_flutter: ^4.8.0
  get: 4.6.6
  get_storage: ^2.1.1
  video_player: ^2.9.2
  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  shared_preferences: 2.3.2
  firebase_messaging: 15.1.3
  flutter_local_notifications: ^17.2.4
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  latlong2: 0.9.1
  url_launcher: ^6.1.6
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0
  geolocator: ^13.0.2
  flutter_compass: ^0.8.1
  connectivity_plus: ^6.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - asset/glowshoess.id.png
    - asset/Facebook.png
    - asset/Google.png
    - asset/user.png
    - asset/lock1.png
    - asset/Image1.png
    - asset/Image2.png
    - asset/Image3.png
    - asset/Image4.png
    - asset/Image5.png
    - asset/Image6.png
    - asset/Image7.png
    - asset/Image8.png
    - asset/profile-picture.png
    - asset/bell.png
    - asset/ping.png
    - asset/banner1.png
    - asset/banner2.png
    - asset/marker-pin.png
    - asset/arrow-bawah.png
    - asset/home.png
    - asset/cart-icon.png
    - asset/history-icon.png
    - asset/user-icon.png
    - asset/one_day_order.png
    - asset/simple_cleaning_logo.png
    - asset/whitening_shoes.png
    - asset/woman_shoes.png
    - asset/kids_shoes.png
    - asset/leather_cleaning.png
    - asset/one_day_order.png
    - asset/change_color.png
    - asset/whitening_logo.png
    - asset/audio/ding.mp3
    - asset/audio/gopay.flac
    - asset/audio/gopay.mp3

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
