name: glowshoess
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: 1.2.2
  webview_flutter: ^4.8.0
  get: 4.6.6
  get_storage: ^2.1.1
  video_player: ^2.9.2
  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  shared_preferences: 2.3.2
  firebase_messaging: 15.1.3
  flutter_local_notifications: ^17.2.4
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  latlong2: 0.9.1
  url_launcher: ^6.1.6
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  get: 4.6.6

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/glowshoess.id.png
    - asset/Facebook.png
    - asset/Google.png
    - asset/user.png
    - asset/lock1.png
    - asset/Image1.png
    - asset/Image2.png
    - asset/Image3.png
    - asset/Image4.png
    - asset/Image5.png
    - asset/Image6.png
    - asset/Image7.png
    - asset/Image8.png
    - asset/profile-picture.png
    - asset/bell.png
    - asset/ping.png
    - asset/Banner_1.png
    - asset/Banner_2.png
    - asset/marker-pin.png
    - asset/arrow-bawah.png
    - asset/home.png
    - asset/cart-icon.png
    - asset/history-icon.png
    - asset/user-icon.png
    - asset/one_day_order.png
    - asset/simple_cleaning_logo.png
    - asset/whitening_shoes.png
    - asset/woman_shoes.png
    - asset/kids_shoes.png
    - asset/leather_cleaning.png
    - asset/one_day_order.png
    - asset/change_color.png
    - asset/whitening_logo.png
    - asset/audio/ding.mp3
    - asset/audio/gopay.flac
    - asset/audio/gopay.mp3
